export const FETCH_POST_REQUEST = 'FETCH_POST_REQUEST';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_ERROR = 'FETCH_POST_ERROR';

export const FETCH_POST_LIKE_REQUEST = 'FETCH_POST_LIKE_REQUEST';
export const FETCH_POST_LIKE_ERROR = 'FETCH_POST_LIKE_ERROR';
export const FETCH_POST_LIKE_SUCCESS = 'FETCH_POST_LIKE_SUCCESS';

export const FETCH_POST_CREATE_REQUEST = 'FETCH_POST_CREATE_REQUEST';
export const FETCH_POST_CREATE_ERROR = 'FETCH_POST_CREATE_ERROR';
export const FETCH_POST_CREATE_SUCCESS = 'FETCH_POST_CREATE_SUCCESS';

export const FETCH_POST_UPDATE_REQUEST = 'FETCH_POST_UPDATE_REQUEST';
export const FETCH_POST_UPDATE_ERROR = 'FETCH_POST_UPDATE_ERROR';
export const FETCH_POST_UPDATE_SUCCESS = 'FETCH_POST_UPDATE_SUCCESS';
